sudo: false

language: python

python:
    - 2.7

install:
    - pip install bs4
    - pip install lxml
    - pip install pandas
    - pip install requests
    - pip install scipy
    - pip install sklearn

script:
    - python pull-stats.py
    - python analyze-games.py --dataset sample-data
    - python monte-carlo-simulation.py --conference "Big Ten Conference" --dataset "sample-data"
