sudo: false

language: python

python:
    - 2.7

install:
    - pip install -r requirements.txt

script:
    - python run-simulator.py --dataset sample-data --skip-save-to-mongodb --skip-pulling-matches daily-simulation
