sudo: false

language: python

python:
    - 2.7

install:
    - pip install -r requirements.txt

script:
    - docker pull roclark/clarktech-ncaab-predictor
    - docker run --rm roclark/clarktech-ncaab-predictor --skip-save-to-mongodb daily-simulation
