sudo: false

language: python

python:
    - 2.7

install:
    - pip install -r requirements.txt

script:
    - python pull-stats.py --skip-pulling-matches
    - python analyze-games.py --dataset sample-data --skip-save-to-mongodb
